//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "characters")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub character_id: i64,
    pub alliance_id: Option<i64>,
    pub corporation_id: i64,
    pub birthday: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub user_id: Option<i32>,
    pub main: bool,
    #[sea_orm(column_type = "Binary(1)", nullable)]
    pub portrait64: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(1)", nullable)]
    pub portrait128: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(1)", nullable)]
    pub portrait256: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(1)", nullable)]
    pub portrait512: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
