//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "corporation_wallet_journal")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub date: i64,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub ref_type: i32,
    pub amount: Option<i64>,
    pub balance: Option<i64>,
    pub context_id: Option<i64>,
    pub context_id_type: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    pub first_party_id: Option<i64>,
    pub second_party_id: Option<i64>,
    pub tax: Option<i64>,
    pub tax_receiver_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
