//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod characters;
pub mod corporation_wallet_journal;
pub mod corporations;
pub mod pap_journal;
pub mod tax_parameters;
pub mod taxable_list;
pub mod users;
