//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pap_journal")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub character_id: i32,
    pub year: i32,
    pub month: i32,
    pub pap: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
