//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::characters::Entity as Characters;
pub use super::corporation_wallet_journal::Entity as CorporationWalletJournal;
pub use super::corporations::Entity as Corporations;
pub use super::pap_journal::Entity as PapJournal;
pub use super::tax_exemption_journal::Entity as TaxExemptionJournal;
pub use super::tax_parameters::Entity as TaxParameters;
pub use super::users::Entity as Users;
